// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Configuration;
using webApiMediaMarkt.Models;

#nullable disable

namespace webApiMediaMarkt.Data
{
    public partial class MediamarktContext : DbContext
    {
        private IConfiguration _Config;

        public MediamarktContext(DbContextOptions<MediamarktContext> options, IConfiguration Config)
            : base(options)
        {
            _Config = Config;
        }

        public virtual DbSet<Producto> Producto { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                //me parece que esto se genero mediante un scaffolding
                optionsBuilder.UseSqlServer(_Config.GetConnectionString("Conexion"));
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<Producto>(entity =>
            {
                entity.Property(e => e.Descripcion).IsRequired();

                entity.Property(e => e.Familia_Producto).IsRequired();

                entity.Property(e => e.Nombre).IsRequired();

                entity.Property(e => e.Precio).HasColumnType("decimal(18, 4)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}